INSERT INTO TEAM (TEAM_NAME) VALUES ('Manchester City');
INSERT INTO TEAM (TEAM_NAME) VALUES ('Chelsea');
INSERT INTO TEAM (TEAM_NAME) VALUES ('Liverpool');

INSERT INTO SEASON (SEASON_PERIOD) VALUES ('2015-2016');
INSERT INTO SEASON (SEASON_PERIOD) VALUES ('2016-2017');
INSERT INTO SEASON (SEASON_PERIOD) VALUES ('2017-2018');

INSERT INTO MATCH (TEAM_HOME_NAME, TEAM_AWAY_NAME, MATCH_HOME_GOALS, MATCH_AWAY_GOALS, MATCH_RESULTS, SEASON_PERIOD) VALUES ('Manchester City', 'Chelsea', '3', '0', 'H', '2015-2016');
INSERT INTO MATCH (TEAM_HOME_NAME, TEAM_AWAY_NAME, MATCH_HOME_GOALS, MATCH_AWAY_GOALS, MATCH_RESULTS, SEASON_PERIOD) VALUES ('Chelsea', 'Liverpool', '1', '2', 'A', '2016-2017');
INSERT INTO MATCH (TEAM_HOME_NAME, TEAM_AWAY_NAME, MATCH_HOME_GOALS, MATCH_AWAY_GOALS, MATCH_RESULTS, SEASON_PERIOD) VALUES ('Liverpool', 'Manchester City', '4', '3', 'H', '2017-2018');